ingress_public_hostname: wiki.tracon.fi

postgres_managed: false
postgres_hostname: siilo.tracon.fi
postgres_database: outlinetracon
postgres_username: outlinetracon
postgres_ssl: true

redis_managed: false
redis_hostname: redis-ha-haproxy.redis-ha.svc.cluster.local
redis_database: 12

outline_secret_managed: false

setup_should_run: true

ingress_letsencrypt_enabled: true
ingress_letsencrypt_cluster_issuer: letsencrypt-prod

aws_upload_bucket_url: https://minio.con2.fi
aws_upload_bucket_name: outlinetracon

smtp_hostname: sr1.pahaip.fi
smtp_from_email: root@tracon.fi

kompassi_team_name: Tracon
kompassi_access_groups:
  - turska-tracon2021-labour-conitea
  - turska-hitpoint2021-labour-conitea
  - traconry-hallitus-nykyinen
kompassi_admin_groups:
  - admins